---
# file: webservers.yml
- hosts: webservers
  become: yes
  vars_files:
    - stage_vars/{{ stage }}.yml
  roles:
    - common

- hosts: webservers
  vars_files:
    - stage_vars/{{ stage }}.yml
  roles:
    - geerlingguy.composer
    - webtier
